production:
  solr:
    hostname: localhost
    ##port: 8983
    port: 8080
    log_level: WARNING
    ##path: /solr/production
    path: /solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    ##port: 8982
    port: 8080
    log_level: INFO
    ##path: /solr/development
    path: /solr

test:
  solr:
    hostname: localhost
    ##port: 8981
    port: 8080
    log_level: WARNING
    ##path: /solr/test
    path: /solr
